# Site settings
title: Marc Bickel's website
email: mrcbickel@gmail.com
url: https://MarcBickel.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
skills: "Computer Vision - Computer Graphics - Computational Photography - User Experience - Deep Learning"
meta_author: Bickel Marc

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: d13636 #18bc9c #80B3FF #eb3434
  primary-rgb: "209, 54, 54" #"24,288,156" #"128,179,255"
  secondary: 2c3e50 #2c3e50 #FD6E8A
  secondary-dark: A2122F #233140 #A2122F

# Footer settings
footer:
  copyright: Marc Bickel
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/mrcbckl
  - title: linkedin
    url: https://www.linkedin.com/in/marc-bickel/
  - title: instagram
    url: http://instagram.com/marcbickel
  - title: github
    url: http://github.com/MarcBickel

# Postal address (add as many lines as necessary)
address:
  - line: 1751 Villars-sur-Glâne, Switzerland

# Credits content
credits: 'This website is based on Freelancer, a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
